name: Java CI with Gradle

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Gradle Wrapper 실행 권한 추가
        run: chmod +x gradlew
      - name: application-server.properties 덮어쓰기
        run: |
          cd ./src/main/resources
          touch ./application-server.properties
          echo "${{ secrets.SETTING_SERVER }}" > ./application-server.properties
        shell: bash
      - name: Gradle로 빌드(CI)
        run: ./gradlew clean build -x test
      - name: 도커허브에 로그인
        uses: docker/login-action@v1
        with:
          username: g6y116
          password: ${{ secrets.DOCKER_USER_PW }}
      - name: 이미지 빌드
        run: docker build -t g6y116/noveling .
      - name: 도커허브에 이미지 푸시
        run: docker push g6y116/noveling
      - name: AWS EC2에 ssh 접속 후 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_IP }}
          port: 22
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            docker pull g6y116/noveling
            docker-compose up -d